name: Validate and merge Pull request
on:
  pull_request_target:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      pr_owner:
        type: string
        default: 'modbus2mqtt'
        description: Enter Pull Request owner
      pr_number:
        type: string
        default: '33'
        description: Enter Pull Request number
permissions: write-all
jobs:
  validate_and_release:
    runs-on: ubuntu-latest
    environment: validate
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Sparse checkout modbus2mqtt
        run: |
          git clone --filter=blob:none --sparse \
            https://github.com/modbus2mqtt/modbus2mqtt.git m2m-server
          cd m2m-server
          git sparse-checkout set backend .npmrc .nvmrc package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: m2m-server/package.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: m2m-server/.nvmrc
          cache: pnpm
          cache-dependency-path: m2m-server/backend/pnpm-lock.yaml

      - name: Install backend dependencies and build
        run: |
          cd m2m-server/backend
          pnpm install --frozen-lockfile
          pnpm run build

      - name: set PR_NUMBER
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo PR_NUMBER=${{ inputs.pr_number }} >> $GITHUB_ENV

      - name: set PR_NUMBER from event
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo PR_NUMBER=${{ github.event.number }} >> $GITHUB_ENV

      - name: Check out modbus2mqtt.config
        uses: actions/checkout@v4
        with:
          path: 'modbus2mqtt'

      - name: Validate specifications
        id: validate_specs
        run: node m2m-server/dist/specification/validate.js --pr_number ${{ env.PR_NUMBER }} --pr_owner ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: automerge
        if: ${{ steps.validate_specs.outputs.SPECS_ONLY != '' }}
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ env.PR_NUMBER }}
          MERGE_LABELS: ""
