name: Validate and merge Pull request
on:
  repository_dispatch:
    types: [create-pull-request]
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:
    inputs:
      pr_owner:
        type: string
        default: 'modbus2mqtt'
        description: Enter Pull Request owner
      pr_number:
        type: string
        default: '33'
        description: Enter Pull Request number
permissions: 
  contents: write
  issues: write
  pull-requests: write
jobs:
  validate_and_release:
    runs-on: ubuntu-latest
    environment: validate
    permissions:
      pull-requests: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: echo '{} ' >package.json
      - run: npm install @modbus2mqtt/specification
      - name: set PR_NUMBER
        if:  ${{ github.event_name == 'workflow_dispatch' }}
        run: echo PR_NUMBER=${{ inputs.pr_number }} >> $GITHUB_ENV
      - name: set PR_NUMBER from event
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run:   echo PR_NUMBER=${{ github.event.number }} >> $GITHUB_ENV
      - name: Check out
        uses: actions/checkout@v4
        with:
          path: 'local'
      - uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ env.PR_NUMBER }} 
          message: |
            **Hello**
            üåè
            !
      - run: node node_modules/@modbus2mqtt/specification/dist/validate.js --pr_number  ${{ env.PR_NUMBER }} --pr_owner ${{github.repository_owner}}
        id: validate_specs
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
