name: Validate and merge Pull request
on:
  pull_request:
    types: opened, reopened
  workflow_dispatch:
    inputs:
      pr_owner:
        type: string
        default: 'volkmarnissen'
        description: Enter Pull Request owner
      pr_sha:
        type: string
        default: '6bcda01ef2c772d93fcf47d74c516d0056bf87ac'
        description: Enter Pull Request sha
permissions: write-all
jobs:
  validate_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: echo '{} ' >package.json
      - run: npm install @modbus2mqtt/specification
      - name: set PR_NUMBER
        if:  ${{ github.event_name == 'workflow_dispatch' }}
        run: echo PR_NUMBER=${{ inputs.pr_number }} >> $GITHUB_ENV
      - name: set PR_NUMBER from event
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run:   echo PR_NUMBER=${{ github.event.number }} >> $GITHUB_ENV
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          sha: ${{ inputs.pr_sha}}
        id: PR
      - run:   echo ${{ env.prNumber }}  ${{ env.prCreatedAt }}  ${{ env.prMergedAt }}
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          
      - run: npx validate --pr_number  ${{ env.prNumber }} --pr_mergedAt  ${{ env.prMergedAt }} --pr_createdAt  ${{ env.prCreatedAt }}
        if: steps.PR.outputs.pr_found == 'true'
        env:
          # JSON object with the full PR object
          prNumber: ${{ steps.PR.outputs.number }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"        
        with:
          PULL_REQUEST: ${{ env.prNumber }}
